spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tiny_task
    username: tiny_task
    password: demo123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: validate

servlet:
  multipart:
    max-file-size: 2MB
    max-request-size: 2MB


logging:
  level:
    com.coyoapp.tinytask: DEBUG
