spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tiny_task
    username: tiny_task
    password: demo123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: validate

  servlet:
    multipart:
      max-request-size: 4MB
      max-file-size: 4MB

server:
  tomcat:
    max-swallow-size: 4MB

logging:
  level:
    com.coyoapp.tinytask: DEBUG
